"use client";

// import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import { PropsWithChildren } from "react";
import "../styles/globals.css";
import { GlobalContextProvider } from "@/context/store";

const kanit = Kanit({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-kanit",
});
// export const metadata: Metadata = {
//   title: "Green Energy Plus",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={kanit.variable}>
      <GlobalContextProvider>
        <body>{children}</body>
      </GlobalContextProvider>
    </html>
  );
}
